server:
  applicationConnectors:
    - type: http
      port: 8080

database:
  driverClass: org.postgresql.Driver
  user: MyUser
  password: MyPassword
  url: jdbc:postgresql://localhost:5432/MyDatabase